### ISSUE TITLE
TMB installation with appveyor

### ISSUE THREAD

**Issue by joethorley** [kaskr/adcomp#226]
I'm trying to test a R package I wrote <https://github.com/poissonconsulting/tmbr>  that uses TMB on appveyor <https://ci.appveyor.com/project/joethorley/tmbr>

In short the tests error out on TMB::compile. The tests are passed on my OSX machine and travis.

The appveyor script is as follows. I've run out of tricks. If someone was able to provide an appveyor script for installing and using TMB I would be really grateful.

```
# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

# Adapt as necessary starting from here

environment:
  global:
    R_ARCH: x64
    USE_RTOOLS: true
    GCC_PATH: mingw_64

build_script:
  - travis-tool.sh install_r TMB
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
```
